name: 'Deploy to Needle Cloud'
description: 'Automate deployments to Needle Cloud with Github actions'
branding:
  icon: 'upload-cloud'
  color: 'blue'
author: Needle
inputs:
  token:
    description: 'Needle Cloud Access Token (requires write permissions)'
    required: true
  name:
    description: 'Needle Cloud Project Name'
    required: false
  dir:
    description: 'Directory to deploy'
    required: false
  next:
    description: 'Using the needle-cloud@next package version'
    required: false
  webhookUrl:
    description: 'Webhook URL to notify on deployment completion'
    required: false
  no-unfurl:
    description: 'Prevent unfurling of URLs in the webhook message'
    required: false
    default: 'false'
outputs:
  url:
    description: 'Deployment URL'
runs:
  using: 'node20'
  main: 'dist/index.js'